version: "3.4"

networks:
  crawler_internal:
    driver: bridge

services:
  elastic_search:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    networks:
      - crawler_internal

  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.6.2'
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - crawler_internal

  elastic_search_ui:
    image: appbaseio/dejavu
    container_name: elastic_search_ui
    ports:
      - "1358:1358"

  protobuf_sender_ui:
    image: gusaul/grpcox:latest
    container_name: protobuf_sender_ui
    ports:
      - "6969:6969"
    volumes:
      - /log:/log
      
  spark:
    image: hronosf/vk-crawler-spark-base-image
    build: 
      dockerfile: ./Dockerfile
      context: ./util/
    container_name: spark
    user: root
    environment:
      - SPARK_MODE=master
    ports:  
      - '8080:8080'
      - '7077:7077'
    networks:
        - crawler_internal
        
  spark-worker:
    image: hronosf/vk-crawler-spark-base-image
    build: 
      dockerfile: ./Dockerfile
      context: ./util/
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=6
    networks:
        - crawler_internal
    links: 
          - spark
    
  proxy:
    container_name: proxy
    image: envoyproxy/envoy-alpine:v1.14.1
    networks:
      - crawler_internal
    restart: on-failure
    ports:
      - 9901:9901
      - 10000:10000
      - 10001:10001
    volumes:
      - ./util/envoy/envoy.yaml:/etc/envoy/envoy.yaml

  vk-proxy-auth:
    container_name: vk-proxy-auth
    image: hronosf/vk-crawler-proxy-auth
    build:
      dockerfile: proxy-for-vk/Dockerfile_proxy_1
      context: ./util/
    networks:
      - crawler_internal
    restart: on-failure
    ports:
      - 8010:8010

  vk-proxy-api:
    container_name: vk-proxy-api
    image: hronosf/vk-crawler-proxy-api
    build:
      dockerfile: proxy-for-vk/Dockerfile_proxy_2
      context: ./util/
    networks:
        - crawler_internal
    restart: on-failure
    ports:
      - 8020:8020 