version: '3.4'

x-infra: &infra-variables
  SPARK_CORES_MAX: 1
  ES_ADDRESS: elasticsearch
  SPARK_ADDRESS: spark://spark:7077

networks:
  vk-crawler_crawler_internal:
    external: true
    
services:
  java-crawler:
    container_name: java-crawler
    image: hronosf/vk-crawler-java-crawler
    build:
      dockerfile: java-crawler/Dockerfile
      context: .
      args:
          <<: *infra-variables
          VK_APP_KEY: 8316dfb98316dfb98316dfb9ee836518c6883168316dfb9dc4e32d3d3de2f857ccbd94e
          VK_APP_ID: 7587711
    ports:
      - "9090:9090"
      - "9087:8080"
    networks:
      - vk-crawler_crawler_internal
    restart: on-failure

  java-data-processing:
    container_name: java-data-processing
    image: hronosf/vk-crawler-java-data-processing
    build:
      dockerfile: java-data-processing/Dockerfile
      context: .
      args:
           <<: *infra-variables
    networks:
      - vk-crawler_crawler_internal
    depends_on: 
      - python-summarization-service
      - python-relationship-extractor-service
    restart: on-failure

  java-search-engine:
    container_name: java-search-engine
    image: hronosf/vk-crawler-java-search-engine
    build:
      dockerfile: java-search-engine/Dockerfile
      context: .
      args:
           <<: *infra-variables
    ports:
        - "9091:9091"
        - "9092:8080"
    networks:
        - vk-crawler_crawler_internal
    restart: on-failure
    
  python-relationship-extractor-service:
    container_name:  python-relationship-extractor-service
    image: hronosf/vk-crawler-python-relationship-extractor-service
    build:
        dockerfile: python-relationship-extractor/Dockerfile
        context: .
        args:
           <<: *infra-variables
    ports:
      - "6067:6067"
    networks:
      - vk-crawler_crawler_internal
    restart: on-failure
  
  python-summarization-service:
    container_name: python-summarization-service
    image: hronosf/vk-crawler-python-summarization-service
    build:
        dockerfile: python-summarizer/Dockerfile
        context: .
        args:
           <<: *infra-variables
    ports:
      - "6066:6066"
    networks:
       - vk-crawler_crawler_internal
    restart: on-failure